## Modis folder analysis

In [2]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
from glob import glob
from tqdm import tqdm
from data_loader_analysis import Modis_data_loader
from data_loader_analysis import PM_25_dataloader
from data_loader_analysis import combine_the_data_frames

### Modis data analysis

In [3]:
Modis_data_2018 = Modis_data_loader("MODIS_AOD/merged_data_2018_sorted_dates.csv")

In [4]:
Modis_data_2018.get_head()
# The data is of 365 days latitude and longitude hence the )

,latitude,longitude,2018-01-01,2018-01-02,2018-01-03,2018-01-04,2018-01-05,2018-01-06,2018-01-07,2018-01-08,...,2018-12-22,2018-12-23,2018-12-24,2018-12-25,2018-12-26,2018-12-27,2018-12-28,2018-12-29,2018-12-30,2018-12-31
0,28.414,77.171,NaN,0.322,NaN,0.816,1.422,2.179,1.117,NaN,...,0.552,0.933,1.650,0.921,NaN,0.554,NaN,0.906,NaN,NaN
1,28.414,77.181,NaN,0.305,NaN,NaN,1.360,2.154,1.069,NaN,...,0.543,0.936,1.620,0.884,NaN,0.522,NaN,0.893,NaN,1.329
2,28.414,77.192,NaN,0.293,NaN,NaN,1.337,2.130,1.059,NaN,...,0.550,0.954,1.626,0.870,NaN,0.516,NaN,0.897,NaN,1.334
3,28.414,77.202,NaN,0.305,NaN,NaN,1.314,2.129,1.047,NaN,...,0.570,0.973,1.654,0.863,NaN,0.533,NaN,0.899,NaN,1.335
4,28.414,77.213,NaN,0.319,NaN,NaN,1.327,2.147,1.050,NaN,...,0.591,1.009,1.703,0.879,NaN,0.579,NaN,0.919,NaN,1.362
5,28.414,77.223,NaN,0.331,NaN,NaN,1.362,2.163,1.085,NaN,...,0.610,1.056,1.716,0.910,NaN,0.616,NaN,0.938,NaN,1.380
6,28.424,77.171,NaN,0.328,NaN,0.806,1.476,2.159,1.157,NaN,...,0.546,0.980,1.696,1.004,NaN,0.597,NaN,0.919,NaN,NaN
7,28.424,77.181,NaN,0.328,NaN,0.807,1.430,2.141,1.116,NaN,...,0.554,0.961,1.666,0.937,NaN,0.569,NaN,0.919,NaN,NaN
8,28.424,77.192,NaN,0.317,NaN,NaN,1.372,2.134,1.079,NaN,...,0.550,0.951,1.634,0.887,NaN,0.535,NaN,0.914,NaN,1.359
9,28.424,77.202,NaN,0.307,NaN,NaN,1.348,2.115,1.070,NaN,...,0.549,0.965,1.622,0.885,NaN,0.527,NaN,0.916,NaN,1.354
10,28.424,77.213,NaN,0.341,NaN,NaN,1.352,2.136,1.092,NaN,...,0.595,1.036,1.701,0.915,NaN,0.601,NaN,NaN,NaN,NaN
11,28.424,77.223,NaN,0.348,NaN,NaN,1.376,2.148,1.117,NaN,...,NaN,1.069,1.711,0.928,NaN,0.629,NaN,NaN,NaN,NaN
12,28.424,77.233,NaN,0.327,NaN,NaN,1.363,2.138,1.094,NaN,...,0.612,1.084,1.702,0.905,NaN,0.632,NaN,0.962,NaN,1.412
13,28.424,77.244,NaN,0.310,NaN,0.910,1.327,2.113,1.078,NaN,...,0.608,1.061,1.671,0.865,NaN,0.611,NaN,0.958,NaN,1.411
14,28.434,77.161,NaN,0.393,NaN,0.774,1.614,2.298,1.197,NaN,...,0.520,1.047,1.662,1.093,NaN,0.630,NaN,0.893,NaN,NaN
15,28.434,77.171,NaN,0.356,NaN,0.793,1.582,2.208,1.198,NaN,...,0.533,1.049,1.672,1.095,NaN,0.648,NaN,0.918,NaN,NaN
16,28.434,77.181,NaN,0.327,NaN,0.806,1.533,2.121,1.157,NaN,...,0.546,1.026,1.675,1.044,NaN,0.630,NaN,0.930,NaN,1.397
17,28.434,77.192,NaN,0.311,NaN,0.803,1.434,2.065,1.096,NaN,...,0.554,0.988,1.615,0.920,NaN,0.555,NaN,0.929,NaN,1.382
18,28.434,77.202,NaN,0.300,NaN,0.811,1.381,2.060,1.092,NaN,...,0.552,0.982,1.599,0.914,NaN,0.546,NaN,0.929,NaN,1.373
19,28.434,77.213,NaN,0.314,NaN,NaN,1.353,2.082,1.115,NaN,...,0.573,0.992,1.632,0.911,NaN,0.562,NaN,0.932,NaN,1.374

In [5]:
Modis_data_2018.get_shape()

(1350, 367)

In [6]:
Modis_data_2019 = Modis_data_loader("MODIS_AOD/merged_data_2019_sorted_dates.csv")
Modis_data_2019.get_head()

,latitude,longitude,2019-01-01,2019-01-02,2019-01-03,2019-01-04,2019-01-05,2019-01-06,2019-01-07,2019-01-08,...,2019-12-22,2019-12-23,2019-12-24,2019-12-25,2019-12-26,2019-12-27,2019-12-28,2019-12-29,2019-12-30,2019-12-31
0,28.414,77.171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.132,...,NaN,NaN,NaN,NaN,0.531,NaN,NaN,NaN,NaN,NaN
1,28.414,77.181,NaN,NaN,NaN,NaN,1.930,NaN,NaN,1.105,...,NaN,NaN,NaN,NaN,0.658,NaN,NaN,NaN,NaN,NaN
2,28.414,77.192,NaN,NaN,NaN,NaN,1.910,NaN,NaN,1.101,...,NaN,NaN,NaN,NaN,0.636,NaN,NaN,NaN,NaN,NaN
3,28.414,77.202,NaN,NaN,NaN,NaN,1.925,NaN,0.709,1.104,...,NaN,NaN,NaN,NaN,0.608,NaN,NaN,NaN,NaN,NaN
4,28.414,77.213,NaN,NaN,NaN,NaN,1.959,NaN,NaN,1.135,...,NaN,NaN,NaN,NaN,0.615,NaN,NaN,NaN,NaN,NaN
5,28.414,77.223,1.149,NaN,NaN,NaN,1.987,NaN,NaN,1.174,...,NaN,NaN,NaN,NaN,0.633,NaN,NaN,NaN,NaN,NaN
6,28.424,77.171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.182,...,NaN,NaN,NaN,NaN,0.634,NaN,NaN,NaN,NaN,NaN
7,28.424,77.181,NaN,NaN,NaN,NaN,2.004,NaN,NaN,1.136,...,NaN,NaN,NaN,NaN,0.609,NaN,NaN,NaN,NaN,NaN
8,28.424,77.192,NaN,NaN,NaN,NaN,1.958,NaN,NaN,1.106,...,NaN,NaN,NaN,NaN,0.580,NaN,NaN,NaN,NaN,NaN
9,28.424,77.202,NaN,NaN,NaN,NaN,1.938,NaN,NaN,1.104,...,NaN,NaN,NaN,NaN,0.629,NaN,NaN,NaN,NaN,NaN
10,28.424,77.213,NaN,NaN,NaN,NaN,1.992,NaN,NaN,1.159,...,NaN,NaN,NaN,NaN,0.692,NaN,NaN,NaN,NaN,NaN
11,28.424,77.223,NaN,NaN,NaN,NaN,2.006,NaN,NaN,1.186,...,NaN,NaN,NaN,NaN,0.721,NaN,NaN,NaN,NaN,NaN
12,28.424,77.233,1.153,NaN,NaN,NaN,2.008,NaN,NaN,1.205,...,NaN,NaN,NaN,NaN,0.717,NaN,NaN,NaN,NaN,NaN
13,28.424,77.244,1.166,NaN,NaN,NaN,1.995,NaN,0.743,1.185,...,NaN,NaN,NaN,NaN,0.681,NaN,NaN,NaN,NaN,NaN
14,28.434,77.161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.250,...,NaN,NaN,NaN,NaN,0.666,NaN,NaN,NaN,NaN,NaN
15,28.434,77.171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.246,...,NaN,NaN,NaN,NaN,0.646,NaN,NaN,NaN,NaN,NaN
16,28.434,77.181,NaN,NaN,NaN,NaN,2.063,NaN,NaN,1.222,...,NaN,NaN,NaN,NaN,0.633,NaN,NaN,NaN,NaN,NaN
17,28.434,77.192,1.131,NaN,NaN,NaN,1.987,NaN,NaN,1.146,...,NaN,NaN,NaN,NaN,0.618,NaN,NaN,NaN,NaN,NaN
18,28.434,77.202,1.135,NaN,NaN,NaN,1.961,NaN,NaN,1.136,...,NaN,NaN,NaN,NaN,0.628,NaN,NaN,NaN,NaN,NaN
19,28.434,77.213,1.153,NaN,NaN,NaN,1.967,NaN,NaN,1.143,...,NaN,NaN,NaN,NaN,0.635,NaN,NaN,NaN,NaN,NaN

In [7]:
Modis_data_2019.get_shape()

(1350, 367)

In [8]:
Modis_data_2020 = Modis_data_loader("MODIS_AOD/merged_data_2020_sorted_dates.csv")
Modis_data_2020.get_head()

,latitude,longitude,2020-01-01,2020-01-02,2020-01-03,2020-01-04,2020-01-05,2020-01-06,2020-01-07,2020-01-08,...,2020-12-22,2020-12-23,2020-12-24,2020-12-25,2020-12-26,2020-12-27,2020-12-28,2020-12-29,2020-12-30,2020-12-31
0,28.414,77.171,NaN,NaN,1.428,1.092,NaN,NaN,NaN,NaN,...,NaN,0.491,NaN,NaN,NaN,0.390,0.531,NaN,0.549,NaN
1,28.414,77.181,NaN,NaN,1.389,1.077,NaN,NaN,NaN,NaN,...,NaN,0.493,NaN,NaN,NaN,0.368,0.515,NaN,0.530,NaN
2,28.414,77.192,NaN,NaN,1.325,1.085,NaN,NaN,NaN,NaN,...,NaN,0.482,NaN,NaN,NaN,0.363,0.506,NaN,0.518,NaN
3,28.414,77.202,NaN,NaN,1.306,1.106,NaN,NaN,NaN,NaN,...,NaN,0.483,NaN,NaN,NaN,0.375,0.505,NaN,0.525,NaN
4,28.414,77.213,NaN,NaN,1.312,1.157,NaN,NaN,NaN,NaN,...,NaN,0.495,NaN,NaN,NaN,0.392,0.532,NaN,0.555,NaN
5,28.414,77.223,NaN,NaN,1.301,NaN,NaN,NaN,NaN,NaN,...,NaN,0.519,NaN,NaN,NaN,0.406,0.565,NaN,0.601,NaN
6,28.424,77.171,NaN,NaN,1.462,1.137,NaN,NaN,NaN,NaN,...,NaN,0.504,NaN,NaN,NaN,0.426,0.564,NaN,0.596,NaN
7,28.424,77.181,NaN,NaN,1.448,1.114,NaN,NaN,NaN,NaN,...,NaN,0.513,NaN,NaN,NaN,0.407,0.538,NaN,0.561,NaN
8,28.424,77.192,NaN,NaN,1.423,1.101,NaN,NaN,NaN,NaN,...,NaN,0.508,NaN,0.583,NaN,0.372,0.513,NaN,0.536,NaN
9,28.424,77.202,NaN,NaN,1.378,1.099,NaN,NaN,NaN,NaN,...,NaN,0.491,NaN,0.549,NaN,0.358,0.500,NaN,0.524,NaN
10,28.424,77.213,NaN,NaN,1.356,1.181,NaN,NaN,NaN,NaN,...,NaN,0.517,NaN,NaN,NaN,0.398,0.550,NaN,0.580,NaN
11,28.424,77.223,NaN,NaN,1.343,1.239,NaN,NaN,NaN,NaN,...,NaN,0.530,NaN,NaN,NaN,0.404,0.568,NaN,0.610,NaN
12,28.424,77.233,NaN,NaN,1.308,1.275,NaN,NaN,NaN,NaN,...,NaN,0.514,NaN,0.493,NaN,0.382,0.572,NaN,0.581,NaN
13,28.424,77.244,NaN,NaN,1.263,1.245,NaN,NaN,NaN,NaN,...,NaN,0.471,NaN,0.504,NaN,0.361,0.536,0.93,0.551,NaN
14,28.434,77.161,NaN,NaN,1.459,1.191,NaN,NaN,NaN,NaN,...,NaN,0.458,NaN,0.664,NaN,0.406,0.555,NaN,0.622,NaN
15,28.434,77.171,NaN,NaN,1.471,1.186,NaN,NaN,NaN,NaN,...,NaN,0.487,NaN,NaN,NaN,0.427,0.590,NaN,0.627,NaN
16,28.434,77.181,NaN,NaN,1.466,1.172,NaN,NaN,NaN,NaN,...,NaN,0.520,NaN,NaN,NaN,0.427,0.579,NaN,0.626,NaN
17,28.434,77.192,NaN,NaN,1.431,1.112,NaN,NaN,NaN,NaN,...,NaN,0.516,NaN,0.583,NaN,0.384,0.498,NaN,0.557,NaN
18,28.434,77.202,NaN,NaN,1.420,1.096,NaN,NaN,NaN,NaN,...,NaN,0.503,NaN,0.549,NaN,0.368,0.487,NaN,0.549,NaN
19,28.434,77.213,NaN,NaN,1.407,1.103,NaN,NaN,NaN,NaN,...,NaN,0.503,NaN,0.539,NaN,0.387,0.497,NaN,0.562,NaN

In [9]:
Modis_data_2020.get_shape()

(1350, 368)

In [10]:
Modis_data_2021 = Modis_data_loader("MODIS_AOD/merged_data_2021_sorted_dates.csv")
Modis_data_2021.get_head()

,latitude,longitude,2021-01-01,2021-01-02,2021-01-03,2021-01-04,2021-01-05,2021-01-06,2021-01-07,2021-01-08,...,2021-12-22,2021-12-23,2021-12-24,2021-12-25,2021-12-26,2021-12-27,2021-12-28,2021-12-29,2021-12-30,2021-12-31
0,28.414,77.171,0.586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.931,1.516,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,28.414,77.181,0.570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.902,1.527,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28.414,77.192,0.561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.869,1.577,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,28.414,77.202,0.581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.874,1.651,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,28.414,77.213,0.595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.892,1.589,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,28.414,77.223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.898,1.672,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,28.424,77.171,0.623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.573,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,28.424,77.181,0.608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.923,1.415,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,28.424,77.192,0.583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.890,1.510,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,28.424,77.202,0.570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.846,1.607,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,28.424,77.213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.859,1.669,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,28.424,77.223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.869,1.786,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,28.424,77.233,0.597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.859,1.575,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,28.424,77.244,0.583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.852,1.533,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,28.434,77.161,0.601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.494,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,28.434,77.171,0.622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.533,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,28.434,77.181,0.648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.572,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,28.434,77.192,0.615,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.905,1.492,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,28.434,77.202,0.594,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.860,1.552,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,28.434,77.213,0.610,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.858,1.555,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
Modis_data_2021 = Modis_data_loader("MODIS_AOD/merged_data_2021_sorted_dates.csv")
Modis_data_2021.get_head()

,latitude,longitude,2021-01-01,2021-01-02,2021-01-03,2021-01-04,2021-01-05,2021-01-06,2021-01-07,2021-01-08,...,2021-12-22,2021-12-23,2021-12-24,2021-12-25,2021-12-26,2021-12-27,2021-12-28,2021-12-29,2021-12-30,2021-12-31
0,28.414,77.171,0.586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.931,1.516,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,28.414,77.181,0.570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.902,1.527,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28.414,77.192,0.561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.869,1.577,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,28.414,77.202,0.581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.874,1.651,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,28.414,77.213,0.595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.892,1.589,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,28.414,77.223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.898,1.672,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,28.424,77.171,0.623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.573,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,28.424,77.181,0.608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.923,1.415,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,28.424,77.192,0.583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.890,1.510,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,28.424,77.202,0.570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.846,1.607,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,28.424,77.213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.859,1.669,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,28.424,77.223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.869,1.786,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,28.424,77.233,0.597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.859,1.575,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,28.424,77.244,0.583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.852,1.533,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,28.434,77.161,0.601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.494,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,28.434,77.171,0.622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.533,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,28.434,77.181,0.648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.572,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,28.434,77.192,0.615,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.905,1.492,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,28.434,77.202,0.594,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.860,1.552,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,28.434,77.213,0.610,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.858,1.555,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
Modis_data_2021.get_shape()

(1350, 367)

In [13]:
Modis_data_2022 = Modis_data_loader("MODIS_AOD/merged_data_2022_sorted_dates.csv")
Modis_data_2022.get_head()

,latitude,longitude,2021-12-31,2022-01-02,2022-01-03,2022-01-04,2022-01-05,2022-01-06,2022-01-07,2022-01-08,...,2022-12-22,2022-12-23,2022-12-24,2022-12-25,2022-12-26,2022-12-27,2022-12-28,2022-12-29,2022-12-30,2022-12-31
0,28.414,77.171,NaN,1.001,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.486,NaN,NaN,NaN,0.452,NaN,NaN,NaN,NaN
1,28.414,77.181,NaN,0.898,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.513,NaN,NaN,NaN,0.477,NaN,NaN,NaN,NaN
2,28.414,77.192,NaN,0.883,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.533,NaN,NaN,NaN,0.490,NaN,NaN,NaN,NaN
3,28.414,77.202,NaN,0.867,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.545,NaN,NaN,NaN,0.505,NaN,NaN,NaN,NaN
4,28.414,77.213,NaN,0.860,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.557,NaN,NaN,NaN,0.512,NaN,NaN,NaN,NaN
5,28.414,77.223,NaN,0.868,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.592,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,28.424,77.171,NaN,1.205,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.443,NaN,NaN,NaN,0.425,NaN,NaN,NaN,NaN
7,28.424,77.181,NaN,1.024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.486,NaN,NaN,NaN,0.461,NaN,NaN,NaN,NaN
8,28.424,77.192,NaN,0.919,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.509,NaN,NaN,NaN,0.476,NaN,NaN,NaN,NaN
9,28.424,77.202,NaN,0.895,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.534,NaN,NaN,NaN,0.489,NaN,NaN,NaN,NaN
10,28.424,77.213,NaN,0.904,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.508,NaN,NaN,NaN,NaN
11,28.424,77.223,NaN,0.922,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,28.424,77.233,NaN,0.950,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.571,NaN,NaN,NaN,0.523,NaN,NaN,NaN,NaN
13,28.424,77.244,NaN,0.965,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.569,NaN,NaN,NaN,0.533,NaN,NaN,NaN,NaN
14,28.434,77.161,NaN,1.448,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.439,NaN,NaN,NaN,0.357,NaN,NaN,NaN,NaN
15,28.434,77.171,NaN,1.352,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.440,NaN,NaN,NaN,0.401,NaN,NaN,NaN,NaN
16,28.434,77.181,NaN,1.197,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.452,NaN,NaN,NaN,0.436,NaN,NaN,NaN,NaN
17,28.434,77.192,NaN,0.943,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.521,NaN,NaN,NaN,0.482,NaN,NaN,NaN,NaN
18,28.434,77.202,NaN,0.913,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.545,NaN,NaN,NaN,0.492,NaN,NaN,NaN,NaN
19,28.434,77.213,NaN,0.909,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.539,NaN,NaN,NaN,0.505,NaN,NaN,NaN,NaN

In [14]:
Modis_data_2022.get_shape()

(1350, 367)

In [15]:
Modis_data_2023 = Modis_data_loader("MODIS_AOD/merged_data_2023_sorted_dates.csv")
Modis_data_2023.get_head()

,latitude,longitude,2023-01-01,2023-01-02,2023-01-03,2023-01-04,2023-01-05,2023-01-06,2023-01-07,2023-01-08,...,2023-09-16,2023-09-17,2023-09-18,2023-09-19,2023-09-20,2023-09-21,2023-09-22,2023-09-23,2023-09-24,2023-09-25
0,28.414,77.171,0.317,NaN,0.567,0.339,0.375,0.322,NaN,NaN,...,1.128,0.707,NaN,NaN,NaN,0.438,0.465,NaN,0.668,NaN
1,28.414,77.181,0.329,NaN,0.573,0.349,0.375,0.336,NaN,NaN,...,1.141,0.648,NaN,NaN,NaN,0.412,0.391,NaN,0.600,NaN
2,28.414,77.192,0.334,NaN,0.571,0.363,0.373,0.342,NaN,NaN,...,1.142,0.638,NaN,NaN,NaN,0.384,0.394,NaN,0.601,NaN
3,28.414,77.202,0.339,NaN,0.588,0.368,0.385,0.338,NaN,NaN,...,1.175,0.644,NaN,NaN,NaN,0.404,0.417,NaN,0.661,NaN
4,28.414,77.213,0.345,NaN,0.605,0.373,0.398,0.355,NaN,NaN,...,1.211,0.702,NaN,NaN,NaN,0.431,0.472,NaN,0.716,NaN
5,28.414,77.223,0.346,NaN,0.604,0.381,0.397,0.364,NaN,NaN,...,NaN,0.725,NaN,NaN,NaN,0.428,0.498,NaN,0.720,NaN
6,28.424,77.171,0.316,NaN,0.571,0.332,0.377,0.330,NaN,NaN,...,NaN,0.793,NaN,NaN,NaN,0.451,0.533,NaN,0.798,NaN
7,28.424,77.181,0.329,NaN,0.578,0.342,0.386,0.345,NaN,NaN,...,1.153,0.753,NaN,NaN,NaN,0.446,0.475,NaN,0.687,NaN
8,28.424,77.192,0.326,NaN,0.579,0.355,0.379,0.339,NaN,NaN,...,1.146,0.693,NaN,NaN,NaN,0.410,0.411,NaN,0.590,NaN
9,28.424,77.202,0.329,NaN,0.577,0.371,0.373,0.340,NaN,NaN,...,1.132,0.687,NaN,NaN,NaN,0.362,0.394,NaN,0.560,NaN
10,28.424,77.213,0.341,NaN,0.619,0.373,0.403,0.358,NaN,NaN,...,1.209,0.761,NaN,NaN,NaN,0.422,0.474,NaN,0.794,NaN
11,28.424,77.223,NaN,NaN,0.619,0.370,0.403,0.364,NaN,NaN,...,1.247,0.764,NaN,NaN,NaN,0.415,0.463,NaN,NaN,NaN
12,28.424,77.233,0.323,NaN,0.604,0.370,0.384,0.364,NaN,NaN,...,NaN,0.792,NaN,NaN,NaN,0.386,NaN,NaN,0.753,NaN
13,28.424,77.244,0.322,NaN,0.595,0.358,0.368,0.320,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.359,0.381,NaN,0.679,NaN
14,28.434,77.161,0.275,NaN,0.541,0.352,0.331,0.262,NaN,NaN,...,NaN,0.728,NaN,NaN,NaN,0.468,0.505,NaN,NaN,NaN
15,28.434,77.171,0.298,NaN,0.558,0.352,0.353,0.304,NaN,NaN,...,NaN,0.814,NaN,NaN,NaN,0.431,0.576,NaN,0.878,NaN
16,28.434,77.181,0.315,NaN,0.575,0.356,0.375,0.345,NaN,NaN,...,1.169,0.779,NaN,NaN,NaN,0.424,0.556,NaN,0.815,NaN
17,28.434,77.192,0.323,NaN,0.582,0.363,0.372,0.344,NaN,NaN,...,1.120,0.714,NaN,NaN,NaN,0.390,0.438,NaN,0.610,NaN
18,28.434,77.202,0.327,NaN,0.583,0.381,0.367,0.348,NaN,NaN,...,1.113,0.695,NaN,NaN,NaN,0.355,0.417,NaN,0.571,NaN
19,28.434,77.213,0.333,NaN,0.601,0.379,0.378,0.342,NaN,NaN,...,1.146,0.721,NaN,NaN,NaN,0.370,0.437,NaN,0.679,NaN

In [16]:
Modis_data_2023.get_shape()

(1350, 250)

### Latitude & Longitude data sets

In [17]:
Lat_Long_data = Modis_data_loader("Stations_Lat_Long/stn_extrafeat.csv")
stations = Lat_Long_data.data[["Latitude", "Longitude"]]
stations

     Latitude  Longitude
0   28.815329  77.153010
1   28.646835  77.316032
2   28.695381  77.181665
3   28.470691  77.109936
4   28.776200  77.051074
5   28.725650  77.201157
6   28.551201  77.273574
7   28.656756  77.227234
8   28.750050  77.111261
9   28.498571  77.264840
10  28.571027  77.071901
11  28.655602  77.285932
12  28.562776  77.118005
13  28.681174  77.302523
14  28.631694  77.249439
15  28.732820  77.170633
16  28.580280  77.233829
17  28.588333  77.221667
18  28.591825  77.227307
19  28.611281  77.237738
20  28.636429  77.201067
21  28.684678  77.076574
22  28.609090  77.032541
23  28.570173  76.933762
24  28.822836  77.101981
25  28.567890  77.250515
26  28.657381  77.158545
27  28.530785  77.271255
28  28.623748  77.287205
29  28.563262  77.186937
30  28.645000  77.167000
31  28.639645  77.146262
32  28.674045  77.131023
33  28.732528  77.119920
34  28.651478  77.147311
35  28.550425  77.215938
36  28.710508  77.249485
37  28.531346  77.190156
38  28.672342  77.315260
39  28.699793  77.165453

## PM_2.5 data set

In [18]:
# Shape of the raw dataset.
PM_data = PM_25_dataloader()
PM_data.get_shape()

(16, 40, 8760)

##### Shape of the data set is `(8760, 40, 16)` from here we have seen that there are 8760 hours in a year and 40 stations and 16 features in the data set but we have extracted the PM_25 data values for 40 stations and 8760 time stamps.

In [20]:
PM_data = PM_25_dataloader()
PM_data = PM_data.get_data()
PM_data_with_Lat_long = combine_the_data_frames(stations, PM_data)
PM_data_with_Lat_long.head()

,Latitude,Longitude,0,1,2,3,4,5,6,7,...,8750,8751,8752,8753,8754,8755,8756,8757,8758,8759
0,28.815329,77.153010,265.333344,341.500000,323.333344,340.000000,132.166672,106.833336,162.166672,241.666672,...,272.333344,369.333344,335.000000,275.666656,261.333344,325.666656,226.000000,223.666672,279.000000,343.000000
1,28.646835,77.316032,571.666687,366.833344,421.250000,335.500000,154.833328,106.833336,256.416656,725.666687,...,268.500000,268.166656,262.666656,225.166672,243.000000,240.666672,171.833328,169.500000,302.833344,456.500000
2,28.695381,77.181665,437.833344,327.666656,427.000000,376.500000,169.666672,157.833328,437.000000,749.166687,...,338.500000,382.833344,349.666656,273.833344,259.166656,245.833328,196.333328,163.333328,325.333344,476.000000
3,28.470691,77.109936,550.376648,619.489990,465.200012,304.130005,143.858337,122.298332,203.143326,323.450012,...,275.351654,283.111664,237.164993,208.151672,192.948334,185.583328,161.544998,161.471664,261.464996,244.146667
4,28.776200,77.051074,688.000000,417.333344,382.333344,451.333344,232.000000,163.000000,388.000000,746.755066,...,351.166656,447.666656,390.333344,300.500000,270.666656,257.166656,228.500000,218.500000,391.500000,375.833344