## Modis folder analysis

In [37]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
from glob import glob
from tqdm import tqdm
from data_loader_analysis import Modis_data_loader
from data_loader_analysis import PM_25_dataloader
from data_loader_analysis import combine_the_data_frames
from data_loader_analysis import Training_data_loader

### Modis data analysis

In [38]:
Modis_data_2018 = Modis_data_loader("MODIS_AOD/merged_data_2018_sorted_dates.csv")

In [39]:
Modis_data_2018.get_head()
# The data is of 365 days latitude and longitude hence the )

,latitude,longitude,2018-01-01,2018-01-02,2018-01-03,2018-01-04,2018-01-05,2018-01-06,2018-01-07,2018-01-08,...,2018-12-22,2018-12-23,2018-12-24,2018-12-25,2018-12-26,2018-12-27,2018-12-28,2018-12-29,2018-12-30,2018-12-31
0,28.414,77.171,NaN,0.322,NaN,0.816,1.422,2.179,1.117,NaN,...,0.552,0.933,1.650,0.921,NaN,0.554,NaN,0.906,NaN,NaN
1,28.414,77.181,NaN,0.305,NaN,NaN,1.360,2.154,1.069,NaN,...,0.543,0.936,1.620,0.884,NaN,0.522,NaN,0.893,NaN,1.329
2,28.414,77.192,NaN,0.293,NaN,NaN,1.337,2.130,1.059,NaN,...,0.550,0.954,1.626,0.870,NaN,0.516,NaN,0.897,NaN,1.334
3,28.414,77.202,NaN,0.305,NaN,NaN,1.314,2.129,1.047,NaN,...,0.570,0.973,1.654,0.863,NaN,0.533,NaN,0.899,NaN,1.335
4,28.414,77.213,NaN,0.319,NaN,NaN,1.327,2.147,1.050,NaN,...,0.591,1.009,1.703,0.879,NaN,0.579,NaN,0.919,NaN,1.362
5,28.414,77.223,NaN,0.331,NaN,NaN,1.362,2.163,1.085,NaN,...,0.610,1.056,1.716,0.910,NaN,0.616,NaN,0.938,NaN,1.380
6,28.424,77.171,NaN,0.328,NaN,0.806,1.476,2.159,1.157,NaN,...,0.546,0.980,1.696,1.004,NaN,0.597,NaN,0.919,NaN,NaN
7,28.424,77.181,NaN,0.328,NaN,0.807,1.430,2.141,1.116,NaN,...,0.554,0.961,1.666,0.937,NaN,0.569,NaN,0.919,NaN,NaN
8,28.424,77.192,NaN,0.317,NaN,NaN,1.372,2.134,1.079,NaN,...,0.550,0.951,1.634,0.887,NaN,0.535,NaN,0.914,NaN,1.359
9,28.424,77.202,NaN,0.307,NaN,NaN,1.348,2.115,1.070,NaN,...,0.549,0.965,1.622,0.885,NaN,0.527,NaN,0.916,NaN,1.354
10,28.424,77.213,NaN,0.341,NaN,NaN,1.352,2.136,1.092,NaN,...,0.595,1.036,1.701,0.915,NaN,0.601,NaN,NaN,NaN,NaN
11,28.424,77.223,NaN,0.348,NaN,NaN,1.376,2.148,1.117,NaN,...,NaN,1.069,1.711,0.928,NaN,0.629,NaN,NaN,NaN,NaN
12,28.424,77.233,NaN,0.327,NaN,NaN,1.363,2.138,1.094,NaN,...,0.612,1.084,1.702,0.905,NaN,0.632,NaN,0.962,NaN,1.412
13,28.424,77.244,NaN,0.310,NaN,0.910,1.327,2.113,1.078,NaN,...,0.608,1.061,1.671,0.865,NaN,0.611,NaN,0.958,NaN,1.411
14,28.434,77.161,NaN,0.393,NaN,0.774,1.614,2.298,1.197,NaN,...,0.520,1.047,1.662,1.093,NaN,0.630,NaN,0.893,NaN,NaN
15,28.434,77.171,NaN,0.356,NaN,0.793,1.582,2.208,1.198,NaN,...,0.533,1.049,1.672,1.095,NaN,0.648,NaN,0.918,NaN,NaN
16,28.434,77.181,NaN,0.327,NaN,0.806,1.533,2.121,1.157,NaN,...,0.546,1.026,1.675,1.044,NaN,0.630,NaN,0.930,NaN,1.397
17,28.434,77.192,NaN,0.311,NaN,0.803,1.434,2.065,1.096,NaN,...,0.554,0.988,1.615,0.920,NaN,0.555,NaN,0.929,NaN,1.382
18,28.434,77.202,NaN,0.300,NaN,0.811,1.381,2.060,1.092,NaN,...,0.552,0.982,1.599,0.914,NaN,0.546,NaN,0.929,NaN,1.373
19,28.434,77.213,NaN,0.314,NaN,NaN,1.353,2.082,1.115,NaN,...,0.573,0.992,1.632,0.911,NaN,0.562,NaN,0.932,NaN,1.374

In [40]:
Modis_data_2018.get_shape()

(1350, 367)

In [41]:
Modis_data_2019 = Modis_data_loader("MODIS_AOD/merged_data_2019_sorted_dates.csv")
Modis_data_2019.get_head()

,latitude,longitude,2019-01-01,2019-01-02,2019-01-03,2019-01-04,2019-01-05,2019-01-06,2019-01-07,2019-01-08,...,2019-12-22,2019-12-23,2019-12-24,2019-12-25,2019-12-26,2019-12-27,2019-12-28,2019-12-29,2019-12-30,2019-12-31
0,28.414,77.171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.132,...,NaN,NaN,NaN,NaN,0.531,NaN,NaN,NaN,NaN,NaN
1,28.414,77.181,NaN,NaN,NaN,NaN,1.930,NaN,NaN,1.105,...,NaN,NaN,NaN,NaN,0.658,NaN,NaN,NaN,NaN,NaN
2,28.414,77.192,NaN,NaN,NaN,NaN,1.910,NaN,NaN,1.101,...,NaN,NaN,NaN,NaN,0.636,NaN,NaN,NaN,NaN,NaN
3,28.414,77.202,NaN,NaN,NaN,NaN,1.925,NaN,0.709,1.104,...,NaN,NaN,NaN,NaN,0.608,NaN,NaN,NaN,NaN,NaN
4,28.414,77.213,NaN,NaN,NaN,NaN,1.959,NaN,NaN,1.135,...,NaN,NaN,NaN,NaN,0.615,NaN,NaN,NaN,NaN,NaN
5,28.414,77.223,1.149,NaN,NaN,NaN,1.987,NaN,NaN,1.174,...,NaN,NaN,NaN,NaN,0.633,NaN,NaN,NaN,NaN,NaN
6,28.424,77.171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.182,...,NaN,NaN,NaN,NaN,0.634,NaN,NaN,NaN,NaN,NaN
7,28.424,77.181,NaN,NaN,NaN,NaN,2.004,NaN,NaN,1.136,...,NaN,NaN,NaN,NaN,0.609,NaN,NaN,NaN,NaN,NaN
8,28.424,77.192,NaN,NaN,NaN,NaN,1.958,NaN,NaN,1.106,...,NaN,NaN,NaN,NaN,0.580,NaN,NaN,NaN,NaN,NaN
9,28.424,77.202,NaN,NaN,NaN,NaN,1.938,NaN,NaN,1.104,...,NaN,NaN,NaN,NaN,0.629,NaN,NaN,NaN,NaN,NaN
10,28.424,77.213,NaN,NaN,NaN,NaN,1.992,NaN,NaN,1.159,...,NaN,NaN,NaN,NaN,0.692,NaN,NaN,NaN,NaN,NaN
11,28.424,77.223,NaN,NaN,NaN,NaN,2.006,NaN,NaN,1.186,...,NaN,NaN,NaN,NaN,0.721,NaN,NaN,NaN,NaN,NaN
12,28.424,77.233,1.153,NaN,NaN,NaN,2.008,NaN,NaN,1.205,...,NaN,NaN,NaN,NaN,0.717,NaN,NaN,NaN,NaN,NaN
13,28.424,77.244,1.166,NaN,NaN,NaN,1.995,NaN,0.743,1.185,...,NaN,NaN,NaN,NaN,0.681,NaN,NaN,NaN,NaN,NaN
14,28.434,77.161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.250,...,NaN,NaN,NaN,NaN,0.666,NaN,NaN,NaN,NaN,NaN
15,28.434,77.171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.246,...,NaN,NaN,NaN,NaN,0.646,NaN,NaN,NaN,NaN,NaN
16,28.434,77.181,NaN,NaN,NaN,NaN,2.063,NaN,NaN,1.222,...,NaN,NaN,NaN,NaN,0.633,NaN,NaN,NaN,NaN,NaN
17,28.434,77.192,1.131,NaN,NaN,NaN,1.987,NaN,NaN,1.146,...,NaN,NaN,NaN,NaN,0.618,NaN,NaN,NaN,NaN,NaN
18,28.434,77.202,1.135,NaN,NaN,NaN,1.961,NaN,NaN,1.136,...,NaN,NaN,NaN,NaN,0.628,NaN,NaN,NaN,NaN,NaN
19,28.434,77.213,1.153,NaN,NaN,NaN,1.967,NaN,NaN,1.143,...,NaN,NaN,NaN,NaN,0.635,NaN,NaN,NaN,NaN,NaN

In [42]:
Modis_data_2019.get_shape()

(1350, 367)

In [43]:
Modis_data_2020 = Modis_data_loader("MODIS_AOD/merged_data_2020_sorted_dates.csv")
Modis_data_2020.get_head()

,latitude,longitude,2020-01-01,2020-01-02,2020-01-03,2020-01-04,2020-01-05,2020-01-06,2020-01-07,2020-01-08,...,2020-12-22,2020-12-23,2020-12-24,2020-12-25,2020-12-26,2020-12-27,2020-12-28,2020-12-29,2020-12-30,2020-12-31
0,28.414,77.171,NaN,NaN,1.428,1.092,NaN,NaN,NaN,NaN,...,NaN,0.491,NaN,NaN,NaN,0.390,0.531,NaN,0.549,NaN
1,28.414,77.181,NaN,NaN,1.389,1.077,NaN,NaN,NaN,NaN,...,NaN,0.493,NaN,NaN,NaN,0.368,0.515,NaN,0.530,NaN
2,28.414,77.192,NaN,NaN,1.325,1.085,NaN,NaN,NaN,NaN,...,NaN,0.482,NaN,NaN,NaN,0.363,0.506,NaN,0.518,NaN
3,28.414,77.202,NaN,NaN,1.306,1.106,NaN,NaN,NaN,NaN,...,NaN,0.483,NaN,NaN,NaN,0.375,0.505,NaN,0.525,NaN
4,28.414,77.213,NaN,NaN,1.312,1.157,NaN,NaN,NaN,NaN,...,NaN,0.495,NaN,NaN,NaN,0.392,0.532,NaN,0.555,NaN
5,28.414,77.223,NaN,NaN,1.301,NaN,NaN,NaN,NaN,NaN,...,NaN,0.519,NaN,NaN,NaN,0.406,0.565,NaN,0.601,NaN
6,28.424,77.171,NaN,NaN,1.462,1.137,NaN,NaN,NaN,NaN,...,NaN,0.504,NaN,NaN,NaN,0.426,0.564,NaN,0.596,NaN
7,28.424,77.181,NaN,NaN,1.448,1.114,NaN,NaN,NaN,NaN,...,NaN,0.513,NaN,NaN,NaN,0.407,0.538,NaN,0.561,NaN
8,28.424,77.192,NaN,NaN,1.423,1.101,NaN,NaN,NaN,NaN,...,NaN,0.508,NaN,0.583,NaN,0.372,0.513,NaN,0.536,NaN
9,28.424,77.202,NaN,NaN,1.378,1.099,NaN,NaN,NaN,NaN,...,NaN,0.491,NaN,0.549,NaN,0.358,0.500,NaN,0.524,NaN
10,28.424,77.213,NaN,NaN,1.356,1.181,NaN,NaN,NaN,NaN,...,NaN,0.517,NaN,NaN,NaN,0.398,0.550,NaN,0.580,NaN
11,28.424,77.223,NaN,NaN,1.343,1.239,NaN,NaN,NaN,NaN,...,NaN,0.530,NaN,NaN,NaN,0.404,0.568,NaN,0.610,NaN
12,28.424,77.233,NaN,NaN,1.308,1.275,NaN,NaN,NaN,NaN,...,NaN,0.514,NaN,0.493,NaN,0.382,0.572,NaN,0.581,NaN
13,28.424,77.244,NaN,NaN,1.263,1.245,NaN,NaN,NaN,NaN,...,NaN,0.471,NaN,0.504,NaN,0.361,0.536,0.93,0.551,NaN
14,28.434,77.161,NaN,NaN,1.459,1.191,NaN,NaN,NaN,NaN,...,NaN,0.458,NaN,0.664,NaN,0.406,0.555,NaN,0.622,NaN
15,28.434,77.171,NaN,NaN,1.471,1.186,NaN,NaN,NaN,NaN,...,NaN,0.487,NaN,NaN,NaN,0.427,0.590,NaN,0.627,NaN
16,28.434,77.181,NaN,NaN,1.466,1.172,NaN,NaN,NaN,NaN,...,NaN,0.520,NaN,NaN,NaN,0.427,0.579,NaN,0.626,NaN
17,28.434,77.192,NaN,NaN,1.431,1.112,NaN,NaN,NaN,NaN,...,NaN,0.516,NaN,0.583,NaN,0.384,0.498,NaN,0.557,NaN
18,28.434,77.202,NaN,NaN,1.420,1.096,NaN,NaN,NaN,NaN,...,NaN,0.503,NaN,0.549,NaN,0.368,0.487,NaN,0.549,NaN
19,28.434,77.213,NaN,NaN,1.407,1.103,NaN,NaN,NaN,NaN,...,NaN,0.503,NaN,0.539,NaN,0.387,0.497,NaN,0.562,NaN

In [44]:
Modis_data_2020.get_shape()

(1350, 368)

In [45]:
Modis_data_2021 = Modis_data_loader("MODIS_AOD/merged_data_2021_sorted_dates.csv")
Modis_data_2021.get_head()

,latitude,longitude,2021-01-01,2021-01-02,2021-01-03,2021-01-04,2021-01-05,2021-01-06,2021-01-07,2021-01-08,...,2021-12-22,2021-12-23,2021-12-24,2021-12-25,2021-12-26,2021-12-27,2021-12-28,2021-12-29,2021-12-30,2021-12-31
0,28.414,77.171,0.586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.931,1.516,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,28.414,77.181,0.570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.902,1.527,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28.414,77.192,0.561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.869,1.577,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,28.414,77.202,0.581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.874,1.651,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,28.414,77.213,0.595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.892,1.589,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,28.414,77.223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.898,1.672,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,28.424,77.171,0.623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.573,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,28.424,77.181,0.608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.923,1.415,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,28.424,77.192,0.583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.890,1.510,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,28.424,77.202,0.570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.846,1.607,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,28.424,77.213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.859,1.669,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,28.424,77.223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.869,1.786,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,28.424,77.233,0.597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.859,1.575,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,28.424,77.244,0.583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.852,1.533,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,28.434,77.161,0.601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.494,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,28.434,77.171,0.622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.533,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,28.434,77.181,0.648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.572,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,28.434,77.192,0.615,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.905,1.492,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,28.434,77.202,0.594,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.860,1.552,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,28.434,77.213,0.610,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.858,1.555,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
Modis_data_2021 = Modis_data_loader("MODIS_AOD/merged_data_2021_sorted_dates.csv")
Modis_data_2021.get_head()

,latitude,longitude,2021-01-01,2021-01-02,2021-01-03,2021-01-04,2021-01-05,2021-01-06,2021-01-07,2021-01-08,...,2021-12-22,2021-12-23,2021-12-24,2021-12-25,2021-12-26,2021-12-27,2021-12-28,2021-12-29,2021-12-30,2021-12-31
0,28.414,77.171,0.586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.931,1.516,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,28.414,77.181,0.570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.902,1.527,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28.414,77.192,0.561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.869,1.577,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,28.414,77.202,0.581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.874,1.651,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,28.414,77.213,0.595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.892,1.589,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,28.414,77.223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.898,1.672,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,28.424,77.171,0.623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.573,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,28.424,77.181,0.608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.923,1.415,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,28.424,77.192,0.583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.890,1.510,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,28.424,77.202,0.570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.846,1.607,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,28.424,77.213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.859,1.669,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,28.424,77.223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.869,1.786,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,28.424,77.233,0.597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.859,1.575,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,28.424,77.244,0.583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.852,1.533,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,28.434,77.161,0.601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.494,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,28.434,77.171,0.622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.533,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,28.434,77.181,0.648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.572,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,28.434,77.192,0.615,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.905,1.492,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,28.434,77.202,0.594,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.860,1.552,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,28.434,77.213,0.610,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.858,1.555,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
Modis_data_2021.get_shape()

(1350, 367)

In [48]:
Modis_data_2022 = Modis_data_loader("MODIS_AOD/merged_data_2022_sorted_dates.csv")
Modis_data_2022.get_head()

,latitude,longitude,2021-12-31,2022-01-02,2022-01-03,2022-01-04,2022-01-05,2022-01-06,2022-01-07,2022-01-08,...,2022-12-22,2022-12-23,2022-12-24,2022-12-25,2022-12-26,2022-12-27,2022-12-28,2022-12-29,2022-12-30,2022-12-31
0,28.414,77.171,NaN,1.001,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.486,NaN,NaN,NaN,0.452,NaN,NaN,NaN,NaN
1,28.414,77.181,NaN,0.898,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.513,NaN,NaN,NaN,0.477,NaN,NaN,NaN,NaN
2,28.414,77.192,NaN,0.883,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.533,NaN,NaN,NaN,0.490,NaN,NaN,NaN,NaN
3,28.414,77.202,NaN,0.867,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.545,NaN,NaN,NaN,0.505,NaN,NaN,NaN,NaN
4,28.414,77.213,NaN,0.860,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.557,NaN,NaN,NaN,0.512,NaN,NaN,NaN,NaN
5,28.414,77.223,NaN,0.868,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.592,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,28.424,77.171,NaN,1.205,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.443,NaN,NaN,NaN,0.425,NaN,NaN,NaN,NaN
7,28.424,77.181,NaN,1.024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.486,NaN,NaN,NaN,0.461,NaN,NaN,NaN,NaN
8,28.424,77.192,NaN,0.919,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.509,NaN,NaN,NaN,0.476,NaN,NaN,NaN,NaN
9,28.424,77.202,NaN,0.895,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.534,NaN,NaN,NaN,0.489,NaN,NaN,NaN,NaN
10,28.424,77.213,NaN,0.904,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.508,NaN,NaN,NaN,NaN
11,28.424,77.223,NaN,0.922,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,28.424,77.233,NaN,0.950,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.571,NaN,NaN,NaN,0.523,NaN,NaN,NaN,NaN
13,28.424,77.244,NaN,0.965,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.569,NaN,NaN,NaN,0.533,NaN,NaN,NaN,NaN
14,28.434,77.161,NaN,1.448,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.439,NaN,NaN,NaN,0.357,NaN,NaN,NaN,NaN
15,28.434,77.171,NaN,1.352,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.440,NaN,NaN,NaN,0.401,NaN,NaN,NaN,NaN
16,28.434,77.181,NaN,1.197,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.452,NaN,NaN,NaN,0.436,NaN,NaN,NaN,NaN
17,28.434,77.192,NaN,0.943,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.521,NaN,NaN,NaN,0.482,NaN,NaN,NaN,NaN
18,28.434,77.202,NaN,0.913,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.545,NaN,NaN,NaN,0.492,NaN,NaN,NaN,NaN
19,28.434,77.213,NaN,0.909,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.539,NaN,NaN,NaN,0.505,NaN,NaN,NaN,NaN

In [49]:
Modis_data_2022.get_shape()

(1350, 367)

In [50]:
Modis_data_2023 = Modis_data_loader("MODIS_AOD/merged_data_2023_sorted_dates.csv")
Modis_data_2023.get_head()

,latitude,longitude,2023-01-01,2023-01-02,2023-01-03,2023-01-04,2023-01-05,2023-01-06,2023-01-07,2023-01-08,...,2023-09-16,2023-09-17,2023-09-18,2023-09-19,2023-09-20,2023-09-21,2023-09-22,2023-09-23,2023-09-24,2023-09-25
0,28.414,77.171,0.317,NaN,0.567,0.339,0.375,0.322,NaN,NaN,...,1.128,0.707,NaN,NaN,NaN,0.438,0.465,NaN,0.668,NaN
1,28.414,77.181,0.329,NaN,0.573,0.349,0.375,0.336,NaN,NaN,...,1.141,0.648,NaN,NaN,NaN,0.412,0.391,NaN,0.600,NaN
2,28.414,77.192,0.334,NaN,0.571,0.363,0.373,0.342,NaN,NaN,...,1.142,0.638,NaN,NaN,NaN,0.384,0.394,NaN,0.601,NaN
3,28.414,77.202,0.339,NaN,0.588,0.368,0.385,0.338,NaN,NaN,...,1.175,0.644,NaN,NaN,NaN,0.404,0.417,NaN,0.661,NaN
4,28.414,77.213,0.345,NaN,0.605,0.373,0.398,0.355,NaN,NaN,...,1.211,0.702,NaN,NaN,NaN,0.431,0.472,NaN,0.716,NaN
5,28.414,77.223,0.346,NaN,0.604,0.381,0.397,0.364,NaN,NaN,...,NaN,0.725,NaN,NaN,NaN,0.428,0.498,NaN,0.720,NaN
6,28.424,77.171,0.316,NaN,0.571,0.332,0.377,0.330,NaN,NaN,...,NaN,0.793,NaN,NaN,NaN,0.451,0.533,NaN,0.798,NaN
7,28.424,77.181,0.329,NaN,0.578,0.342,0.386,0.345,NaN,NaN,...,1.153,0.753,NaN,NaN,NaN,0.446,0.475,NaN,0.687,NaN
8,28.424,77.192,0.326,NaN,0.579,0.355,0.379,0.339,NaN,NaN,...,1.146,0.693,NaN,NaN,NaN,0.410,0.411,NaN,0.590,NaN
9,28.424,77.202,0.329,NaN,0.577,0.371,0.373,0.340,NaN,NaN,...,1.132,0.687,NaN,NaN,NaN,0.362,0.394,NaN,0.560,NaN
10,28.424,77.213,0.341,NaN,0.619,0.373,0.403,0.358,NaN,NaN,...,1.209,0.761,NaN,NaN,NaN,0.422,0.474,NaN,0.794,NaN
11,28.424,77.223,NaN,NaN,0.619,0.370,0.403,0.364,NaN,NaN,...,1.247,0.764,NaN,NaN,NaN,0.415,0.463,NaN,NaN,NaN
12,28.424,77.233,0.323,NaN,0.604,0.370,0.384,0.364,NaN,NaN,...,NaN,0.792,NaN,NaN,NaN,0.386,NaN,NaN,0.753,NaN
13,28.424,77.244,0.322,NaN,0.595,0.358,0.368,0.320,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.359,0.381,NaN,0.679,NaN
14,28.434,77.161,0.275,NaN,0.541,0.352,0.331,0.262,NaN,NaN,...,NaN,0.728,NaN,NaN,NaN,0.468,0.505,NaN,NaN,NaN
15,28.434,77.171,0.298,NaN,0.558,0.352,0.353,0.304,NaN,NaN,...,NaN,0.814,NaN,NaN,NaN,0.431,0.576,NaN,0.878,NaN
16,28.434,77.181,0.315,NaN,0.575,0.356,0.375,0.345,NaN,NaN,...,1.169,0.779,NaN,NaN,NaN,0.424,0.556,NaN,0.815,NaN
17,28.434,77.192,0.323,NaN,0.582,0.363,0.372,0.344,NaN,NaN,...,1.120,0.714,NaN,NaN,NaN,0.390,0.438,NaN,0.610,NaN
18,28.434,77.202,0.327,NaN,0.583,0.381,0.367,0.348,NaN,NaN,...,1.113,0.695,NaN,NaN,NaN,0.355,0.417,NaN,0.571,NaN
19,28.434,77.213,0.333,NaN,0.601,0.379,0.378,0.342,NaN,NaN,...,1.146,0.721,NaN,NaN,NaN,0.370,0.437,NaN,0.679,NaN

In [51]:
Modis_data_2023.get_shape()

(1350, 250)

### Latitude & Longitude data sets

In [52]:
Lat_Long_data = Modis_data_loader("Stations_Lat_Long/stn_extrafeat.csv")
# stations = Lat_Long_data.data[["Latitude", "Longitude"]]
# stations
Lat_Long_data.data

,ID,Stn,Latitude,Longitude,Pop Density,Very dense,Mod dense,open Forest
0,0,Alipur,28.815329,77.153010,1,0.000250,0.016659,0.020568
1,1,Anand.Vihar,28.646835,77.316032,3,0.000000,0.017812,0.028906
2,2,Ashok.Vihar,28.695381,77.181665,8,0.000250,0.016659,0.020568
3,3,Aya.Nagar,28.470691,77.109936,1,0.010440,0.054480,0.248360
4,4,Bawana,28.776200,77.051074,1,0.000250,0.016659,0.020568
5,5,Burari.Crossing,28.725650,77.201157,2,0.000000,0.050678,0.030847
6,6,CRRI.Mathura.Road,28.551201,77.273574,3,0.010440,0.054480,0.248360
7,7,Chandni.Chowk,28.656756,77.227234,3,0.010440,0.054480,0.248360
8,8,DTU,28.750050,77.111261,1,0.000250,0.016659,0.020568
9,9,Dr..Karni.Singh.Shooting.Range,28.498571,77.264840,6,0.010440,0.054480,0.248360
10,10,Dwarka,28.571027,77.071901,3,0.005629,0.030166,0.063492
11,11,East.Arjun.Nagar,28.655602,77.285932,7,0.000000,0.017812,0.028906
12,12,IGI.Airport.(T3),28.562776,77.118005,1,0.005629,0.030166,0.063492
13,13,IHBAS..Dilshad.Garden,28.681174,77.302523,7,0.000000,0.018667,0.049667
14,14,ITO,28.631694,77.249439,10,0.000000,0.089200,0.112800
15,15,Jahangirpuri,28.732820,77.170633,5,0.000250,0.016659,0.020568
16,16,Jawaharlal.Nehru.Stadium,28.580280,77.233829,3,0.010440,0.054480,0.248360
17,17,Lodhi.RoadIITM,28.588333,77.221667,4,0.047714,0.158000,0.260286
18,18,Lodhi.RoadIMD,28.591825,77.227307,4,0.047714,0.158000,0.260286
19,19,Major.Dhyan.Chand.National.Stadium,28.611281,77.237738,2,0.047714,0.158000,0.260286
20,20,Mandir.Marg,28.636429,77.201067,8,0.047714,0.158000,0.260286
21,21,Mundka,28.684678,77.076574,9,0.000000,0.021860,0.027209
22,22,NSIT.Dwarka,28.609090,77.032541,2,0.005629,0.030166,0.063492
23,23,Najafgarh,28.570173,76.933762,1,0.005629,0.030166,0.063492
24,24,Narela,28.822836,77.101981,1,0.000250,0.016659,0.020568
25,25,Nehru.Nagar,28.567890,77.250515,4,0.010440,0.054480,0.248360
26,26,North.Campus..DU,28.657381,77.158545,6,0.000000,0.021860,0.027209
27,27,Okhla.Phase,28.530785,77.271255,9,0.010440,0.054480,0.248360
28,28,Patparganj,28.623748,77.287205,9,0.000000,0.017812,0.028906
29,29,Punjabi.Bagh,28.563262,77.186937,7,0.005629,0.030166,0.063492
30,30,PusaIMD,28.645000,77.167000,6,0.005629,0.030166,0.063492
31,31,PusaDPCC,28.639645,77.146262,9,0.000000,0.021860,0.027209
32,32,R.K.Puram,28.674045,77.131023,4,0.000000,0.021860,0.027209
33,33,Rohini,28.732528,77.119920,4,0.000250,0.016659,0.020568
34,34,Shadipur,28.651478,77.147311,6,0.000000,0.021860,0.027209
35,35,Sirifort,28.550425,77.215938,7,0.010440,0.054480,0.248360
36,36,Sonia.Vihar,28.710508,77.249485,4,0.000000,0.018667,0.049667
37,37,Sri.Aurobindo.Marg,28.531346,77.190156,4,0.010440,0.054480,0.248360
38,38,Vivek.Vihar,28.672342,77.315260,9,0.000000,0.018667,0.049667
39,39,Wazirpur,28.699793,77.165453,6,0.000250,0.016659,0.020568

In [53]:
stations = Lat_Long_data.data[["Latitude", "Longitude"]]
stations

     Latitude  Longitude
0   28.815329  77.153010
1   28.646835  77.316032
2   28.695381  77.181665
3   28.470691  77.109936
4   28.776200  77.051074
5   28.725650  77.201157
6   28.551201  77.273574
7   28.656756  77.227234
8   28.750050  77.111261
9   28.498571  77.264840
10  28.571027  77.071901
11  28.655602  77.285932
12  28.562776  77.118005
13  28.681174  77.302523
14  28.631694  77.249439
15  28.732820  77.170633
16  28.580280  77.233829
17  28.588333  77.221667
18  28.591825  77.227307
19  28.611281  77.237738
20  28.636429  77.201067
21  28.684678  77.076574
22  28.609090  77.032541
23  28.570173  76.933762
24  28.822836  77.101981
25  28.567890  77.250515
26  28.657381  77.158545
27  28.530785  77.271255
28  28.623748  77.287205
29  28.563262  77.186937
30  28.645000  77.167000
31  28.639645  77.146262
32  28.674045  77.131023
33  28.732528  77.119920
34  28.651478  77.147311
35  28.550425  77.215938
36  28.710508  77.249485
37  28.531346  77.190156
38  28.672342  77.315260
39  28.699793  77.165453

## PM_2.5 data set

In [54]:
# Shape of the raw dataset.
PM_data_instance = PM_25_dataloader()
PM_data_instance.get_shape()

(40, 8760)

##### Shape of the data set is `(8760, 40, 16)` from here we have seen that there are 8760 hours in a year and 40 stations and 16 features in the data set but we have extracted the PM_25 data values for 40 stations and 8760 time stamps.

In [55]:
PM_data = PM_25_dataloader()
PM_data = PM_data.get_data()

# PM_data_with_Lat_long = combine_the_data_frames(stations, PM_data)
# PM_data_with_Lat_long.head()

PM_data.shape

(40, 8760)

### Training data

In [56]:
loader = Training_data_loader(Modis_data_2020.data, Modis_data_2021.data, Modis_data_2022.data, PM_data, stations)

### Extracting all the functional data from the Training data.

In [57]:
loader.daily_PM25_data_extraction()

,2020-01-01,2020-01-02,2020-01-03,2020-01-04,2020-01-05,2020-01-06,2020-01-07,2020-01-08,2020-01-09,2020-01-10,...,2022-12-21,2022-12-22,2022-12-23,2022-12-24,2022-12-25,2022-12-26,2022-12-27,2022-12-28,2022-12-29,2022-12-30
Column1,239.125000,217.708328,192.817535,225.343750,182.916672,169.093750,97.052086,87.039551,80.490089,112.875000,...,172.083328,193.326263,169.125000,151.500000,148.895828,186.833344,157.229156,165.395828,219.541672,283.666656
Column2,367.375031,361.687500,309.965179,235.875000,189.740250,168.430511,142.376663,140.018799,95.112617,148.541672,...,228.333328,270.229156,202.229187,182.708344,199.291672,244.291656,216.583328,175.090225,199.354156,259.020844
Column3,385.333344,376.291687,235.416641,282.729156,195.354156,169.354156,141.645828,132.346420,102.270836,142.187500,...,177.229172,200.958328,202.291656,160.041672,176.416672,202.687500,177.166672,160.534363,217.958344,286.187500
Column4,341.493317,185.562500,193.758331,166.028122,135.367294,118.810417,94.127090,96.653534,62.955002,93.755005,...,168.067703,151.025970,183.546646,133.141663,122.653122,126.844795,110.390205,101.392502,140.599594,206.559570
Column5,433.594391,318.809174,252.058319,267.624359,204.333328,207.416672,139.791672,115.250000,105.500000,147.166656,...,183.124985,183.458344,213.291672,162.625015,164.791672,190.500000,174.500000,156.208328,232.895813,304.124969
Column6,373.533752,339.496063,237.097839,255.008331,191.254944,171.119156,135.287048,126.813019,108.765404,147.886810,...,156.186676,219.750626,149.084167,162.819077,182.170639,219.037781,138.405212,154.448944,179.390411,182.367493
Column7,400.863556,348.464172,207.795410,203.410721,164.618530,146.270630,107.903534,119.322708,91.640419,138.901459,...,184.256241,188.164368,179.920822,130.754791,152.954163,182.298538,133.727509,123.173759,164.349792,190.107559
Column8,365.040588,328.674591,211.695633,221.190002,163.543793,150.272781,124.257904,117.967934,89.779816,129.996765,...,161.175583,152.522156,135.856277,68.665710,59.277882,158.600204,149.610413,126.252579,160.778214,166.064423
Column9,304.324371,251.275848,219.512726,257.288605,192.156845,170.519775,131.311249,110.489578,97.072083,140.195404,...,82.083336,84.708328,72.666664,69.875000,147.957779,139.213654,69.666664,70.041664,94.859283,206.312622
Column10,363.767944,379.616577,203.614609,203.927078,168.583344,140.890274,118.388161,137.135422,101.468750,144.687500,...,234.083344,217.458328,243.187485,180.874985,173.458328,200.916672,162.937500,152.770844,192.916672,264.854156
Column11,472.979187,455.218781,276.093750,214.885437,181.989578,182.302094,119.500000,121.352516,101.979172,144.425217,...,241.209885,204.166672,250.000000,200.083344,179.812500,193.687500,161.229172,178.187500,216.354172,270.416687
Column12,362.947205,327.655548,239.454636,222.427277,169.003586,153.757294,124.951004,123.116302,88.692223,132.910309,...,191.923218,221.324326,194.649582,156.772049,168.277405,203.489136,175.739227,151.998611,193.879669,242.154984
Column13,320.876678,291.574982,257.881653,179.122711,146.294373,140.661469,93.196251,89.037285,63.825211,91.178749,...,184.966461,152.848541,194.980469,145.731873,142.589157,144.168961,114.221245,108.526039,152.824585,202.632706
Column14,314.678131,264.956940,216.939575,189.439590,139.191666,132.640442,91.782288,99.729164,65.118752,104.996872,...,121.831833,158.846832,103.366661,78.775002,96.354164,115.446884,87.283325,101.312500,132.045822,161.571213
Column15,399.656250,400.065796,199.479172,224.250000,149.406250,140.260422,121.708336,114.645836,83.885422,116.687508,...,161.645828,147.437500,183.124985,162.458328,156.041656,168.937500,165.758499,129.708344,175.437500,202.250000
Column16,397.678741,386.481720,268.354156,299.656250,232.572922,196.228394,135.770844,149.802094,158.218750,191.520844,...,221.333328,265.020813,228.086777,204.875000,218.277222,248.895828,194.873642,190.354172,249.166672,305.812500
Column17,444.468689,350.010437,234.343750,209.958344,167.104172,154.795151,119.890419,122.395836,95.197922,140.083328,...,194.583313,215.270844,233.208328,171.896957,188.687500,208.229172,165.687485,157.208328,204.979172,274.750000
Column18,332.005615,271.294037,184.074768,171.575027,135.776184,128.134613,109.125366,138.453384,71.445740,131.521667,...,176.677505,180.319336,203.765808,148.609222,179.617813,225.595123,207.742111,128.969849,175.997910,256.639893
Column19,293.363525,236.003113,162.660416,151.656464,120.684586,115.954590,103.567078,145.489578,59.466457,126.855522,...,128.042084,163.718048,183.340652,112.235626,123.284172,134.437912,120.463760,106.221664,150.799576,205.761871
Column20,365.218781,344.244659,212.284821,204.913559,160.020828,151.510422,128.333328,124.270828,96.739578,142.312500,...,200.187485,225.819183,251.852936,182.083328,193.624985,233.500000,200.208344,162.583328,221.645828,271.687500
Column21,337.471100,301.806091,177.125000,209.239563,157.045380,141.434433,123.483147,116.375000,88.499992,120.114586,...,179.208328,200.854156,206.250000,150.229156,175.312515,204.729156,182.875000,141.854172,180.520828,232.812500
Column22,459.820129,337.718750,219.104172,265.708344,191.697922,182.114578,146.395828,115.072914,105.149063,155.916656,...,236.823441,195.756912,221.857025,190.500000,199.958328,185.062500,204.270828,180.645844,232.208344,313.520813
Column23,359.432495,385.085175,181.155609,183.310349,142.252487,150.924988,109.956467,104.152290,97.408958,143.324173,...,173.616669,216.822937,190.792816,166.385239,188.506363,211.357666,187.539398,210.947662,248.274994,266.181244
Column24,264.750000,276.812500,152.833344,143.229172,150.479172,139.395828,102.083336,94.125008,70.090546,92.713829,...,180.979156,132.541672,174.321136,117.000000,131.520828,113.937500,124.020828,109.506783,161.505615,242.299072
Column25,308.614594,260.645844,176.905472,191.625015,164.416672,158.875000,99.406250,93.947922,84.354172,130.822906,...,190.791672,196.000000,197.416672,163.416672,164.500000,179.250000,156.354156,161.750000,231.770844,312.958313
Column26,509.387695,438.197906,302.351837,281.333344,217.177078,185.645813,125.479164,168.208344,156.458328,214.687500,...,257.729156,275.645813,297.479156,203.583344,228.645844,255.770844,205.562500,213.000015,244.062500,352.895813
Column27,329.639221,275.014374,171.681030,203.107910,128.409180,121.071243,103.807709,92.842087,65.531044,96.491455,...,155.148712,202.416580,173.361679,141.942291,161.601440,178.621887,155.596664,141.031677,199.060211,223.498535
Column28,479.606415,368.875031,231.833328,219.625000,175.458328,155.270828,122.260422,134.916656,106.000000,150.218735,...,223.270844,215.062500,229.520828,164.500000,176.000000,206.145844,163.187500,142.187500,197.958344,277.416656
Column29,367.114594,335.031250,204.239594,209.708328,153.000000,145.156250,117.770844,113.468750,88.687492,128.020828,...,242.937500,286.291687,258.750000,191.895813,208.791672,259.583344,222.062515,169.791656,225.937500,288.979156
Column30,420.677063,364.729187,227.718750,243.645828,161.656265,145.677078,129.562500,111.083328,84.666664,126.510422,...,222.729156,221.666672,230.020844,192.083328,196.354172,202.416672,203.333344,176.937515,211.312485,270.447083
Column31,288.812500,279.437500,225.270844,238.739563,187.156250,164.754272,119.989586,113.893318,111.770828,172.583328,...,196.153610,206.187485,213.166656,194.041672,194.500000,216.583328,220.541656,203.479156,213.729156,260.208313
Column32,234.178543,208.848969,146.828323,164.331879,111.523117,107.736664,86.973747,81.663742,56.425209,88.913338,...,133.634583,151.252090,164.657089,122.712921,128.921875,152.174576,149.264160,131.246674,164.329178,211.599167
Column33,403.093750,283.687500,179.812485,138.781250,117.145836,113.395836,78.510414,86.916664,74.476364,109.177086,...,226.458328,234.708328,243.291656,191.625000,192.083328,202.208344,163.645813,150.895844,193.541672,298.437500
Column34,408.552094,393.072937,270.260406,285.416687,205.500000,186.197922,150.302078,128.817413,111.791664,144.375000,...,197.250000,217.333008,200.541672,181.041672,180.416672,209.645828,170.166672,173.395828,230.937500,290.395813
Column35,389.504120,385.112122,265.535400,261.536865,178.802704,182.903961,150.915833,83.198082,67.919456,101.798546,...,194.647354,221.099548,189.618866,151.870834,161.204163,156.908325,145.252075,169.601212,206.306259,244.512512
Column36,449.536926,334.386200,241.910004,204.434174,174.862000,160.395782,115.417480,121.890259,89.872757,137.781570,...,205.250000,211.416656,220.821518,169.666672,171.666656,188.332672,152.370682,133.958344,181.021973,257.500000
Column37,289.843750,214.322922,163.927078,204.906250,162.458328,157.666656,149.687485,118.125000,79.750000,119.833328,...,167.791672,225.833328,198.583328,167.895828,175.375000,210.604172,175.875000,161.833344,240.612061,269.312500
Column38,338.666656,215.501923,166.833328,161.864594,147.520828,133.927094,112.354164,120.038574,90.143692,119.125008,...,197.458344,181.416656,219.749985,180.958328,162.046768,198.010681,155.958344,139.708328,184.124985,274.937500
Column39,372.366882,332.208344,294.000000,265.430939,206.458328,177.750000,148.666656,146.000000,100.875000,150.770828,...,214.687500,260.020844,215.333328,186.375000,195.041672,235.000000,201.791656,179.833328,224.833344,275.958313
Column40,419.575562,397.399597,303.197937,290.291687,217.239594,197.072922,175.187500,139.519043,114.375000,160.041672,...,173.390610,213.746262,236.267181,177.374985,207.083344,238.958328,230.145844,182.437485,258.127838,326.229187

In [58]:
loader.AOD_data_fusion()

,latitude,longitude,2020-01-01,2020-01-02,2020-01-03,2020-01-04,2020-01-05,2020-01-06,2020-01-07,2020-01-08,...,2022-12-22,2022-12-23,2022-12-24,2022-12-25,2022-12-26,2022-12-27,2022-12-28,2022-12-29,2022-12-30,2022-12-31
0,28.414,77.171,NaN,NaN,1.428,1.092,NaN,NaN,NaN,NaN,...,NaN,0.486,NaN,NaN,NaN,0.452,NaN,NaN,NaN,NaN
1,28.414,77.181,NaN,NaN,1.389,1.077,NaN,NaN,NaN,NaN,...,NaN,0.513,NaN,NaN,NaN,0.477,NaN,NaN,NaN,NaN
2,28.414,77.192,NaN,NaN,1.325,1.085,NaN,NaN,NaN,NaN,...,NaN,0.533,NaN,NaN,NaN,0.490,NaN,NaN,NaN,NaN
3,28.414,77.202,NaN,NaN,1.306,1.106,NaN,NaN,NaN,NaN,...,NaN,0.545,NaN,NaN,NaN,0.505,NaN,NaN,NaN,NaN
4,28.414,77.213,NaN,NaN,1.312,1.157,NaN,NaN,NaN,NaN,...,NaN,0.557,NaN,NaN,NaN,0.512,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,28.864,77.078,NaN,NaN,NaN,1.019,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.520,NaN,NaN,NaN,NaN
1346,28.864,77.088,NaN,NaN,0.881,1.032,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.539,NaN,NaN,NaN,NaN
1347,28.864,77.098,NaN,NaN,0.904,1.031,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.544,NaN,NaN,NaN,NaN
1348,28.864,77.109,NaN,NaN,0.911,1.035,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.570,NaN,NaN,NaN,NaN
1349,28.874,77.088,NaN,NaN,0.836,1.013,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
loader.PM25_nearest_neighbour_finder(loader.AOD_data_fusion())

,latitude,longitude,2020-01-01,2020-01-02,2020-01-03,2020-01-04,2020-01-05,2020-01-06,2020-01-07,2020-01-08,...,2022-12-22,2022-12-23,2022-12-24,2022-12-25,2022-12-26,2022-12-27,2022-12-28,2022-12-29,2022-12-30,2022-12-31
0,28.815,77.150,NaN,NaN,NaN,1.228,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.555,NaN,NaN,NaN,NaN
1,28.649,77.316,NaN,NaN,1.228,1.382,NaN,NaN,NaN,NaN,...,NaN,0.701,NaN,NaN,NaN,0.429,NaN,NaN,0.940,NaN
2,28.698,77.181,NaN,NaN,1.214,1.053,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.476,NaN,NaN,0.676,NaN
3,28.473,77.119,NaN,NaN,1.321,1.168,NaN,NaN,NaN,NaN,...,NaN,0.497,NaN,NaN,NaN,0.361,NaN,NaN,0.740,NaN
4,28.776,77.046,NaN,NaN,NaN,1.196,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.582,NaN,NaN,NaN,NaN
5,28.727,77.202,NaN,NaN,NaN,1.058,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.407,NaN,NaN,NaN,NaN
6,28.551,77.275,NaN,NaN,NaN,1.194,NaN,NaN,NaN,NaN,...,NaN,0.532,NaN,NaN,NaN,0.413,NaN,NaN,NaN,NaN
7,28.659,77.223,NaN,NaN,1.143,1.073,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.425,NaN,NaN,0.925,NaN
8,28.747,77.109,NaN,NaN,NaN,1.222,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.430,NaN,NaN,NaN,NaN
9,28.502,77.264,NaN,NaN,NaN,0.944,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.466,NaN,NaN,NaN,NaN
10,28.571,77.067,NaN,NaN,1.170,1.054,NaN,NaN,NaN,NaN,...,NaN,0.529,NaN,NaN,NaN,0.334,NaN,NaN,NaN,NaN
11,28.659,77.285,NaN,NaN,1.160,1.293,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.441,NaN,NaN,NaN,NaN
12,28.561,77.119,NaN,NaN,1.232,0.986,NaN,NaN,NaN,NaN,...,NaN,0.579,NaN,NaN,NaN,0.386,NaN,NaN,NaN,NaN
13,28.678,77.306,NaN,NaN,1.285,1.170,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.493,NaN,NaN,NaN,NaN
14,28.629,77.254,NaN,NaN,1.221,1.360,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.451,NaN,NaN,0.797,NaN
15,28.737,77.171,NaN,NaN,NaN,1.054,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.423,NaN,NaN,NaN,NaN
16,28.580,77.233,NaN,NaN,1.310,1.212,NaN,NaN,NaN,NaN,...,NaN,0.693,NaN,NaN,NaN,0.377,NaN,NaN,0.890,NaN
17,28.590,77.223,NaN,NaN,1.388,1.154,NaN,NaN,NaN,NaN,...,NaN,0.746,NaN,NaN,NaN,0.425,NaN,NaN,0.764,NaN
18,28.590,77.223,NaN,NaN,1.388,1.154,NaN,NaN,NaN,NaN,...,NaN,0.746,NaN,NaN,NaN,0.425,NaN,NaN,0.764,NaN
19,28.610,77.233,NaN,NaN,1.419,1.339,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.404,NaN,NaN,0.703,NaN
20,28.639,77.202,NaN,NaN,1.189,1.189,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.473,NaN,NaN,NaN,NaN
21,28.688,77.078,NaN,NaN,NaN,1.186,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.410,NaN,NaN,NaN,NaN
22,28.610,77.036,NaN,NaN,NaN,1.203,NaN,NaN,NaN,NaN,...,NaN,0.530,NaN,NaN,NaN,0.410,NaN,NaN,0.801,NaN
23,28.571,76.932,NaN,NaN,NaN,1.230,NaN,NaN,NaN,NaN,...,NaN,0.509,NaN,NaN,NaN,0.421,NaN,NaN,0.778,NaN
24,28.825,77.098,NaN,NaN,NaN,1.180,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.531,NaN,NaN,NaN,NaN
25,28.571,77.254,NaN,NaN,1.405,1.543,NaN,NaN,NaN,NaN,...,NaN,0.594,NaN,NaN,NaN,0.339,NaN,NaN,0.928,NaN
26,28.659,77.161,NaN,NaN,1.164,1.098,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.484,NaN,NaN,0.614,NaN
27,28.531,77.275,NaN,NaN,1.393,1.006,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.407,NaN,NaN,NaN,NaN
28,28.619,77.285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.744,NaN,NaN,NaN,0.446,NaN,NaN,NaN,NaN
29,28.561,77.192,NaN,NaN,1.261,1.273,NaN,NaN,NaN,NaN,...,NaN,0.627,NaN,NaN,NaN,0.362,NaN,NaN,0.769,NaN
30,28.649,77.171,NaN,NaN,1.100,1.152,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.429,NaN,NaN,NaN,NaN
31,28.639,77.150,NaN,NaN,1.127,1.144,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.452,NaN,NaN,0.672,NaN
32,28.678,77.129,NaN,NaN,1.260,1.222,NaN,NaN,NaN,NaN,...,NaN,0.627,NaN,NaN,NaN,0.473,NaN,NaN,NaN,NaN
33,28.737,77.119,NaN,NaN,NaN,1.132,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.405,NaN,NaN,NaN,NaN
34,28.649,77.150,NaN,NaN,1.174,1.106,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.465,NaN,NaN,0.670,NaN
35,28.551,77.213,NaN,NaN,1.396,1.497,NaN,NaN,NaN,NaN,...,NaN,0.550,NaN,NaN,NaN,0.323,NaN,NaN,0.815,NaN
36,28.707,77.254,NaN,NaN,1.125,1.019,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.466,NaN,NaN,NaN,NaN
37,28.531,77.192,NaN,NaN,1.337,1.337,NaN,NaN,NaN,NaN,...,NaN,0.506,NaN,NaN,NaN,0.333,NaN,NaN,NaN,NaN
38,28.668,77.316,NaN,NaN,1.235,1.234,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.451,NaN,NaN,NaN,NaN
39,28.698,77.161,NaN,NaN,NaN,1.121,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.432,NaN,NaN,NaN,NaN

In [60]:
loader.data_cleaning_and_missing_values_handeling(loader.PM25_nearest_neighbour_finder(loader.AOD_data_fusion()))

,latitude,longitude,2020-01-01,2020-01-02,2020-01-03,2020-01-04,2020-01-05,2020-01-06,2020-01-07,2020-01-08,...,2022-12-22,2022-12-23,2022-12-24,2022-12-25,2022-12-26,2022-12-27,2022-12-28,2022-12-29,2022-12-30,2022-12-31
0,28.815,77.150,NaN,NaN,NaN,1.228,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.555,NaN,NaN,NaN,NaN
1,28.649,77.316,NaN,NaN,1.228,1.382,NaN,NaN,NaN,NaN,...,NaN,0.701,NaN,NaN,NaN,0.429,NaN,NaN,0.940,NaN
2,28.698,77.181,NaN,NaN,1.214,1.053,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.476,NaN,NaN,0.676,NaN
3,28.473,77.119,NaN,NaN,1.321,1.168,NaN,NaN,NaN,NaN,...,NaN,0.497,NaN,NaN,NaN,0.361,NaN,NaN,0.740,NaN
4,28.776,77.046,NaN,NaN,NaN,1.196,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.582,NaN,NaN,NaN,NaN
5,28.727,77.202,NaN,NaN,NaN,1.058,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.407,NaN,NaN,NaN,NaN
6,28.551,77.275,NaN,NaN,NaN,1.194,NaN,NaN,NaN,NaN,...,NaN,0.532,NaN,NaN,NaN,0.413,NaN,NaN,NaN,NaN
7,28.659,77.223,NaN,NaN,1.143,1.073,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.425,NaN,NaN,0.925,NaN
8,28.747,77.109,NaN,NaN,NaN,1.222,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.430,NaN,NaN,NaN,NaN
9,28.502,77.264,NaN,NaN,NaN,0.944,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.466,NaN,NaN,NaN,NaN
10,28.571,77.067,NaN,NaN,1.170,1.054,NaN,NaN,NaN,NaN,...,NaN,0.529,NaN,NaN,NaN,0.334,NaN,NaN,NaN,NaN
11,28.659,77.285,NaN,NaN,1.160,1.293,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.441,NaN,NaN,NaN,NaN
12,28.561,77.119,NaN,NaN,1.232,0.986,NaN,NaN,NaN,NaN,...,NaN,0.579,NaN,NaN,NaN,0.386,NaN,NaN,NaN,NaN
13,28.678,77.306,NaN,NaN,1.285,1.170,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.493,NaN,NaN,NaN,NaN
14,28.629,77.254,NaN,NaN,1.221,1.360,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.451,NaN,NaN,0.797,NaN
15,28.737,77.171,NaN,NaN,NaN,1.054,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.423,NaN,NaN,NaN,NaN
16,28.580,77.233,NaN,NaN,1.310,1.212,NaN,NaN,NaN,NaN,...,NaN,0.693,NaN,NaN,NaN,0.377,NaN,NaN,0.890,NaN
17,28.590,77.223,NaN,NaN,1.388,1.154,NaN,NaN,NaN,NaN,...,NaN,0.746,NaN,NaN,NaN,0.425,NaN,NaN,0.764,NaN
18,28.590,77.223,NaN,NaN,1.388,1.154,NaN,NaN,NaN,NaN,...,NaN,0.746,NaN,NaN,NaN,0.425,NaN,NaN,0.764,NaN
19,28.610,77.233,NaN,NaN,1.419,1.339,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.404,NaN,NaN,0.703,NaN
20,28.639,77.202,NaN,NaN,1.189,1.189,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.473,NaN,NaN,NaN,NaN
21,28.688,77.078,NaN,NaN,NaN,1.186,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.410,NaN,NaN,NaN,NaN
22,28.610,77.036,NaN,NaN,NaN,1.203,NaN,NaN,NaN,NaN,...,NaN,0.530,NaN,NaN,NaN,0.410,NaN,NaN,0.801,NaN
23,28.571,76.932,NaN,NaN,NaN,1.230,NaN,NaN,NaN,NaN,...,NaN,0.509,NaN,NaN,NaN,0.421,NaN,NaN,0.778,NaN
24,28.825,77.098,NaN,NaN,NaN,1.180,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.531,NaN,NaN,NaN,NaN
25,28.571,77.254,NaN,NaN,1.405,1.543,NaN,NaN,NaN,NaN,...,NaN,0.594,NaN,NaN,NaN,0.339,NaN,NaN,0.928,NaN
26,28.659,77.161,NaN,NaN,1.164,1.098,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.484,NaN,NaN,0.614,NaN
27,28.531,77.275,NaN,NaN,1.393,1.006,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.407,NaN,NaN,NaN,NaN
28,28.619,77.285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.744,NaN,NaN,NaN,0.446,NaN,NaN,NaN,NaN
29,28.561,77.192,NaN,NaN,1.261,1.273,NaN,NaN,NaN,NaN,...,NaN,0.627,NaN,NaN,NaN,0.362,NaN,NaN,0.769,NaN
30,28.649,77.171,NaN,NaN,1.100,1.152,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.429,NaN,NaN,NaN,NaN
31,28.639,77.150,NaN,NaN,1.127,1.144,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.452,NaN,NaN,0.672,NaN
32,28.678,77.129,NaN,NaN,1.260,1.222,NaN,NaN,NaN,NaN,...,NaN,0.627,NaN,NaN,NaN,0.473,NaN,NaN,NaN,NaN
33,28.737,77.119,NaN,NaN,NaN,1.132,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.405,NaN,NaN,NaN,NaN
34,28.649,77.150,NaN,NaN,1.174,1.106,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.465,NaN,NaN,0.670,NaN
35,28.551,77.213,NaN,NaN,1.396,1.497,NaN,NaN,NaN,NaN,...,NaN,0.550,NaN,NaN,NaN,0.323,NaN,NaN,0.815,NaN
36,28.707,77.254,NaN,NaN,1.125,1.019,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.466,NaN,NaN,NaN,NaN
37,28.531,77.192,NaN,NaN,1.337,1.337,NaN,NaN,NaN,NaN,...,NaN,0.506,NaN,NaN,NaN,0.333,NaN,NaN,NaN,NaN
38,28.668,77.316,NaN,NaN,1.235,1.234,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.451,NaN,NaN,NaN,NaN
39,28.698,77.161,NaN,NaN,NaN,1.121,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.432,NaN,NaN,NaN,NaN

In [61]:
loader.get_final_training_data(loader.data_cleaning_and_missing_values_handeling(loader.PM25_nearest_neighbour_finder(loader.AOD_data_fusion())),loader.daily_PM25_data_extraction()).head(20)

    latitude  longitude       date    AOD       PM2.5
0     28.815      77.15 2020-01-04  1.228  225.343750
1     28.815      77.15 2020-01-10  0.547  112.875000
2     28.815      77.15 2020-01-19  0.716  106.437500
3     28.815      77.15 2020-01-22  1.264  143.676773
4     28.815      77.15 2020-01-26  0.592  217.281235
5     28.815      77.15 2020-01-28  0.538   99.395836
6     28.815      77.15 2020-02-07  0.612  126.331650
7     28.815      77.15 2020-02-11  0.744  161.958328
8     28.815      77.15 2020-02-13  1.016   89.343750
9     28.815      77.15 2020-02-14  0.673   76.145836
10    28.815      77.15 2020-02-16  0.539  175.088745
11    28.815      77.15 2020-02-18  0.403  149.302094
12    28.815      77.15 2020-02-20  0.788  113.991440
13    28.815      77.15 2020-02-21  1.161   38.885063
14    28.815      77.15 2020-02-23  0.891   86.708336
15    28.815      77.15 2020-02-25  0.909  126.276512
16    28.815      77.15 2020-02-28  1.447   95.145836
17    28.815      77.15 2020-02-29  1.086   66.833336
18    28.815      77.15 2020-03-01  0.832   46.874996
19    28.815      77.15 2020-03-03  0.868   96.229156

In [69]:
final_training_data = loader.prepare_final_trainig_data()

Extracting daily Pm2.5 data..
✅ daily_PM_data shape: (40, 1095)
Fusing AOD data from multiple years...
✅ AOD_final shape: (1350, 1098)
Finding nearest neighbours for PM2.5 stations...
✅ nearest_neighbours shape: (40, 1098)
Cleaning data and handling missing values...
✅ Cleaned nearest_neighbours shape: (40, 1097)
Preparing final training data...
✅ final_training_data shape: (15667, 5)

### Final training data
- This is the data from which we can train our

In [63]:
final_training_data

       latitude  longitude       date    AOD       PM2.5
0        28.815     77.150 2020-01-04  1.228  225.343750
1        28.815     77.150 2020-01-10  0.547  112.875000
2        28.815     77.150 2020-01-19  0.716  106.437500
3        28.815     77.150 2020-01-22  1.264  143.676773
4        28.815     77.150 2020-01-26  0.592  217.281235
...         ...        ...        ...    ...         ...
15662    28.698     77.161 2022-12-15  0.252   91.660454
15663    28.698     77.161 2022-12-17  0.288  181.042496
15664    28.698     77.161 2022-12-18  0.245  282.822418
15665    28.698     77.161 2022-12-20  0.736  210.184296
15666    28.698     77.161 2022-12-27  0.432  230.145844

[15667 rows x 5 columns]

In [64]:
def daily_PM25_data_extraction(data):
    data = np.array(data)   
    daily_data = []
    for i in range(8760 // 24):
        nw = np.mean(data[:, i * 24 : (i + 1) * 24], axis=1)
        daily_data.append(nw)
    daily_PM_data = pd.DataFrame(daily_data)
    return daily_PM_data.T

In [65]:
daily_PM25_data_extraction(PM_data).columns

RangeIndex(start=0, stop=365, step=1)

In [66]:
a = np.random.rand(4,8)
a.shape

(4, 8)

In [67]:
a = pd.DataFrame(a)
a

,0,1,2,3,4,5,6,7
0,0.856917,0.130709,0.332551,0.079262,0.246222,0.953469,0.002251,0.261799
1,0.914275,0.115790,0.946097,0.763978,0.152823,0.809394,0.230469,0.652311
2,0.348384,0.346514,0.241386,0.088364,0.134979,0.194581,0.284601,0.952491
3,0.493511,0.561169,0.242936,0.758707,0.981088,0.719838,0.056883,0.390164

In [68]:
a.loc[2]

0    0.348384
1    0.346514
2    0.241386
3    0.088364
4    0.134979
5    0.194581
6    0.284601
7    0.952491
Name: 2, dtype: float64